ITEM_TAG = "item"
LIST_TAG = "list"
REQUEST_TAG = "request"
REQUEST_LIST_TAG = "request-list"
HEADER_TAG = "header"
COOKIE_TAG = "cookie"
EXPORT_TAG = "export"
VARIABLE_TAG = "variable"

HTML_RESPONSE_TYPE = "html"
JSON_RESPONSE_TYPE = "json"

JSON_EXPORT_FORMAT = "json"
CSV_EXPORT_FORMAT = "csv"
EXCEL_EXPORT_FORMAT = "excel"
